// Generated by LiveScript 1.3.1
(function(){
  var Main;
  Main = {};
  Main.Init = function(){
    return this.MainView = function(Elem, IfFirst){
      console.log(IfFirst);
    };
  };
  Main.Init();
  window.Draw = Main;
}).call(this);
