// Generated by LiveScript 1.3.1
(function(){
  var H;
  H = {};
  H.m = require("mithril");
  H._ = require("lodash");
  H.merge = require("merge");
  H.JQ = require("jquery");
  H.TM = require("./TweenMax.min.js");
  H.Pure = require("./Pure.js");
  H.MaxMatch = require("./MaxMatch.js");
  module.exports = H;
}).call(this);
