// Generated by LiveScript 1.3.1
(function(){
  var fs, express, socket, indexhtml, White, LightGreen, Green, RedLight, Red, Brown, RepeatsServerCall, app;
  fs = require("fs");
  express = require("express");
  socket = require("socket.io");
  indexhtml = "<html><script type='text/javascript' src = 'static.js'></script><script type='text/javascript' src = 'main.js'></script></html>";
  White = "\x1b[0;37m";
  LightGreen = "\x1b[1;32m";
  Green = "\x1b[0;32m";
  RedLight = "\x1b[0;31m";
  Red = "\x1b[1;31m";
  Brown = "\x1b[0;33m";
  fs.writeFile("index.html", indexhtml, function(err){
    return console.log(LightGreen + "index.html" + Brown + " created with src " + LightGreen + "main.js" + Brown + " and " + LightGreen + "static.js" + White);
  });
  RepeatsServerCall = 0;
  app = express();
  app.use(function(req, res, next){
    var logString;
    logString = Brown + "Calls:" + LightGreen + RepeatsServerCall + Brown + "|" + LightGreen + req.url + White;
    console.log(logString);
    RepeatsServerCall++;
    return next();
  });
  app.use(express['static'](__dirname));
  app.listen(8080);
}).call(this);
