// Generated by LiveScript 1.3.1
(function(){
  var nv, d3, MyChart;
  nv = require("./nvd3/nv.d3.min.js");
  d3 = require("d3");
  MyChart = {};
  MyChart.CreateSimpleChart = function(data, element){
    return nv.addGraph(function(){
      var chart;
      chart = nv.models.lineChart().margin({
        left: 100
      }).useInteractiveGuideline(true).transitionDuration(350).showLegend(true).showYAxis(true).showXAxis(true);
      console.log(d3);
      chart.xAxis.axisLabel('Time (ms)').tickFormat(d3.format(',r'));
      chart.yAxis.axisLabel('Voltage (v)').tickFormat(d3.format('.02f'));
      nv.utils.windowResize(function(){
        return chart.update();
      });
      d3.select(element).datum(data);
      return chart;
    });
  };
  module.exports = MyChart;
}).call(this);
