(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by LiveScript 1.2.0
(function(){
  var options, errorFn, linkFn;
  if (navigator.webkitGetUserMedia !== null) {
    options = {
      video: true,
      audio: true
    };
    errorFn = function(e){
      return console.log("Error Happened");
    };
    linkFn = function(stream){
      var video;
      video = document.querySelector('video');
      return video.src = window.webkitURL.createObjectURL(stream);
    };
    navigator.webkitGetUserMedia(options, linkFn, errorFn);
  }
}).call(this);

},{}]},{},[1])