// Generated by LiveScript 1.3.1
(function(){
  var OB, log, change;
  OB = {};
  OB.string1 = "hello";
  log = function(X){
    return console.log(JSON.parse(JSON.stringify(X)));
  };
  change = function(x){
    return x.string1 = "love";
  };
  log(change(OB));
  log(OB.string1);
}).call(this);
