// Generated by LiveScript 1.3.1
(function(){
  var H;
  H = {};
  require("mithril");
  H._ = require("prelude-ls");
  H.JQ = require("jquery");
  H.TM = require("./TweenMax.min.js");
  H.tempConv = require("./template-converter.js");
  H.__ = require("underscore");
  H.udc = require("udc");
  H.katex = require("./katex.min.js");
  H.Chart = require("./chart.js/Chart.js");
  H.reg = require("regression");
  module.exports = H;
}).call(this);
