function createfigure(X1, Y1,labels)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 17-Dec-2014 08:54:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.03625 0.076 0.9425 0.866666666666667],...
    'FontSize',16);
grid(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('Imaginary Axis','FontSize',14);

% Create ylabel
ylabel('Real Axis','FontSize',14);

% Create title
title('Eigen Value for linearized System','FontSize',14);

% Create plot
plot(X1,Y1,'MarkerSize',20,'Marker','o','LineWidth',8,'LineStyle','none');

end